### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI-522-Jes-Alex#66]
__Mechanics__
- [ ] Need to have a short project overview in README. Might want to have a nice 'sale pitch' at the beginning to make it more intriguing?
- [ ] Could have explained more on what are the expected input and output of the scripts. 
- [ ] Also, might want to state the dependencies of the scripts, e.g. whose output is whose expected input.

__Quality__
- [ ] In the documentation at the top of each scripts, you can explain what the arguments are in addition to showing an usage example.

__Report__
- [ ] In section 'Exploring The Data', would be nice to state the definitions of these 8 features. I guess 'closest defender (ft)' means distance from the closest defender in feet?
- [ ] Is it possible to center-justify the figure labels and captions?
- [ ] Can we change the plot titles and axis labels from 'Snake_Case' to the usual case?
- [ ] Figures 1-6 are included but not referred to explicitly in text. Need to explain every graphs included.
- [ ] Ideally, each figure should be interpretable on its own with a descriptive and concise caption.

**Comment by jessimk** [comment]
Thanks for your feedback!
